In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("FAKE_NEWS_NET.csv")

In [4]:
df.head()

,title,news_url,source_domain,tweet_num,real
0,Kandi Burruss Explodes Over Rape Accusation on...,http://toofab.com/2017/05/08/real-housewives-a...,toofab.com,42,1
1,People's Choice Awards 2018: The best red carp...,https://www.today.com/style/see-people-s-choic...,www.today.com,0,1
2,Sophia Bush Sends Sweet Birthday Message to 'O...,https://www.etonline.com/news/220806_sophia_bu...,www.etonline.com,63,1
3,Colombian singer Maluma sparks rumours of inap...,https://www.dailymail.co.uk/news/article-33655...,www.dailymail.co.uk,20,1
4,Gossip Girl 10 Years Later: How Upper East Sid...,https://www.zerchoo.com/entertainment/gossip-g...,www.zerchoo.com,38,1

In [5]:
df.tail()

,title,news_url,source_domain,tweet_num,real
23191,Pippa Middleton wedding: In case you missed it...,https://www.express.co.uk/news/royal/807049/pi...,www.express.co.uk,52,1
23192,Zayn Malik & Gigi Hadid’s Shocking Split: Why ...,hollywoodlife.com/2018/03/13/zayn-malik-gigi-h...,hollywoodlife.com,7,0
23193,Jessica Chastain Recalls the Moment Her Mother...,http://www.justjared.com/2018/01/17/jessica-ch...,www.justjared.com,26,1
23194,"Tristan Thompson Feels ""Dumped"" After Khloé Ka...",www.intouchweekly.com/posts/tristan-thompson-f...,www.intouchweekly.com,24,0
23195,Kelly Clarkson Performs a Medley of Kendrick L...,https://www.billboard.com/articles/news/bbma/8...,www.billboard.com,85,1

In [6]:
df.shape

(23196, 5)

In [7]:
df.columns

Index(['title', 'news_url', 'source_domain', 'tweet_num', 'real'], dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 23196 entries, 0 to 23195
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          23196 non-null  str
 1   news_url       22866 non-null  str
 2   source_domain  22866 non-null  str
 3   tweet_num      23196 non-null  int64
 4   real           23196 non-null  int64
dtypes: int64(2), str(3)
memory usage: 4.8 MB

In [9]:
df.describe()

          tweet_num          real
count  23196.000000  23196.000000
mean      88.956803      0.751897
std      488.694592      0.431921
min        0.000000      0.000000
25%       11.000000      1.000000
50%       37.000000      1.000000
75%       65.000000      1.000000
max    29060.000000      1.000000

In [10]:
df.dtypes

title              str
news_url           str
source_domain      str
tweet_num        int64
real             int64
dtype: object

In [11]:
df.isnull().sum()

title              0
news_url         330
source_domain    330
tweet_num          0
real               0
dtype: int64

In [12]:
(df.isnull().sum()/len(df))*100

title            0.000000
news_url         1.422659
source_domain    1.422659
tweet_num        0.000000
real             0.000000
dtype: float64